// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDeviceByIP(arg1) {
  return window['go']['backend']['App']['CheckDeviceByIP'](arg1);
}

export function GetContext() {
  return window['go']['backend']['App']['GetContext']();
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function OpenConfig() {
  return window['go']['backend']['App']['OpenConfig']();
}
