// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backend} from '../models';

export function CheckDeviceByIP(arg1:string):Promise<boolean>;

export function GetContext():Promise<context.Context>;

export function LoadConfig():Promise<backend.Config>;

export function OpenConfig():Promise<string>;
